
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ok
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */static int minutes=2;
     private static String player = "user";
    private static boolean music = false;
    public Menu() {
     //setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        set = new Settings();
     Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocationRelativeTo(null);
this.setResizable(false);
this.setLocation(295,100);


initComponents();
JRootPane s = SwingUtilities.getRootPane(Save);
s.setDefaultButton(Save);
names=set.others();
highscores = set.nothing();
updatetext(set.others(),set.nothing());
buttonGroup1.add(Difficult);
       buttonGroup1.add(Easy);
       buttonGroup1.add(Medium);
       ((PlainDocument)UserName.getDocument()).setDocumentFilter(new some());
    }
    static int getMinutes(){
    return minutes;
    }
    class some extends DocumentFilter{
      @Override
         public void replace(FilterBypass fb, int offset, int length,String text,
               AttributeSet attr) {
         
             if(fb.getDocument().getLength()<9){
                 try {
                     super.replace(fb, offset,length, text, attr);
                 } catch (BadLocationException ex) {
                  
                 }
             }
            
            }
         }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Resume = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        Easy = new javax.swing.JRadioButton();
        Medium = new javax.swing.JRadioButton();
        Difficult = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        higscoresPanel = new javax.swing.JPanel();
        Save1 = new javax.swing.JButton();
        Rank5 = new javax.swing.JLabel();
        Rank4 = new javax.swing.JLabel();
        Rank3 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        Name5 = new javax.swing.JLabel();
        Name4 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Rank2 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        Rank1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Match The Box");
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))).getImage());

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HighScores.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16);
        jLabel16.setBounds(80, 318, 160, 40);

        Resume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Resume.png"))); // NOI18N
        Resume.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Resume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResumeMouseClicked(evt);
            }
        });
        jPanel1.add(Resume);
        Resume.setBounds(80, 188, 160, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainexit.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 448, 160, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Options.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 380, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Start.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 248, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuBackground.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 340, 520);

        jPanel3.add(jPanel1, "card2");

        jPanel2.setLayout(null);

        jLayeredPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));

        jRadioButton1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(246, 11, 49));
        jRadioButton1.setText("Music Effect");
        jRadioButton1.setOpaque(false);
        jLayeredPane1.add(jRadioButton1);
        jRadioButton1.setBounds(20, 130, 150, 30);

        Easy.setText("Easy");
        Easy.setOpaque(false);
        jLayeredPane1.add(Easy);
        Easy.setBounds(30, 210, 80, 23);

        Medium.setSelected(true);
        Medium.setText("Medium");
        Medium.setOpaque(false);
        jLayeredPane1.add(Medium);
        Medium.setBounds(100, 210, 80, 23);

        Difficult.setText("Difficult");
        Difficult.setOpaque(false);
        jLayeredPane1.add(Difficult);
        Difficult.setBounds(180, 210, 61, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Difficulty level:");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(40, 180, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("User Name: ");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(30, 80, 100, 30);

        UserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 51, 0));
        UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserName.setText("User");
        UserName.setBorder(null);
        UserName.setOpaque(false);
        jLayeredPane1.add(UserName);
        UserName.setBounds(130, 80, 140, 30);

        Back.setBackground(new java.awt.Color(255, 0, 51));
        Back.setForeground(new java.awt.Color(255, 255, 0));
        Back.setText("Back");
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.setOpaque(true);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Back);
        Back.setBounds(30, 260, 80, 30);

        Save.setBackground(new java.awt.Color(255, 0, 0));
        Save.setForeground(new java.awt.Color(255, 255, 0));
        Save.setText("OK");
        Save.setBorderPainted(false);
        Save.setContentAreaFilled(false);
        Save.setOpaque(true);
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Save);
        Save.setBounds(170, 260, 80, 30);

        jLabel9.setBackground(new java.awt.Color(255, 51, 0));
        jLabel9.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Settings");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(70, 20, 180, 50);

        jPanel2.add(jLayeredPane1);
        jLayeredPane1.setBounds(20, 70, 280, 310);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 340, 520);

        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(270, 10, 34, 14);

        jPanel3.add(jPanel2, "card3");

        higscoresPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        higscoresPanel.setLayout(null);

        Save1.setBackground(new java.awt.Color(255, 0, 0));
        Save1.setForeground(new java.awt.Color(255, 255, 0));
        Save1.setText("OK");
        Save1.setBorderPainted(false);
        Save1.setContentAreaFilled(false);
        Save1.setOpaque(true);
        Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save1ActionPerformed(evt);
            }
        });
        higscoresPanel.add(Save1);
        Save1.setBounds(100, 430, 100, 30);

        Rank5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Rank5.setText("5");
        Rank5.setVisible(false);
        higscoresPanel.add(Rank5);
        Rank5.setBounds(30, 390, 20, 20);

        Rank4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Rank4.setText("4");
        Rank4.setVisible(false);
        higscoresPanel.add(Rank4);
        Rank4.setBounds(30, 340, 20, 20);

        Rank3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Rank3.setVisible(false);
        Rank3.setText("3");
        higscoresPanel.add(Rank3);
        Rank3.setBounds(30, 290, 20, 20);

        time5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(time5);
        time5.setBounds(220, 390, 90, 20);

        time4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(time4);
        time4.setBounds(220, 340, 90, 20);

        time3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(time3);
        time3.setBounds(220, 290, 90, 20);

        Name5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(Name5);
        Name5.setBounds(100, 390, 80, 20);

        Name4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(Name4);
        Name4.setBounds(100, 340, 80, 20);

        Name3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(Name3);
        Name3.setBounds(100, 290, 80, 20);

        Rank2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Rank2.setVisible(false);
        Rank2.setText("2");
        higscoresPanel.add(Rank2);
        Rank2.setBounds(30, 240, 20, 20);

        Name2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(Name2);
        Name2.setBounds(100, 240, 80, 20);

        Name1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(Name1);
        Name1.setBounds(100, 190, 80, 20);

        time2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(time2);
        time2.setBounds(220, 240, 90, 20);

        time1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        higscoresPanel.add(time1);
        time1.setBounds(220, 190, 90, 30);

        Rank1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Rank1.setText("1");
        Rank1.setVisible(false);
        higscoresPanel.add(Rank1);
        Rank1.setBounds(30, 190, 20, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Rank");
        higscoresPanel.add(jLabel14);
        jLabel14.setBounds(20, 140, 70, 20);

        jLabel11.setFont(new java.awt.Font("Myriad Pro", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("High Scores");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        higscoresPanel.add(jLabel11);
        jLabel11.setBounds(30, 40, 240, 60);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Name");
        higscoresPanel.add(jLabel12);
        jLabel12.setBounds(100, 140, 80, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Time Ellapsed");
        higscoresPanel.add(jLabel13);
        jLabel13.setBounds(200, 130, 120, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        higscoresPanel.add(jLabel10);
        jLabel10.setBounds(3, 1, 400, 550);

        jPanel3.add(higscoresPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private static GameInterface gi;
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
this.dispose();
gi = new GameInterface();
gi.setVisible(true);


    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
System.exit(1);       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        ((CardLayout)jPanel3.getLayout()).show(jPanel3, "card3");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
if(Difficult.isSelected()){
minutes = 1;
}if(Medium.isSelected()){
minutes = 2;
}
if(Easy.isSelected()){
minutes = 5;
}
if(jRadioButton1.isSelected()){
music =true;
}else{music = false;}
player = UserName.getText();
       ((CardLayout)jPanel3.getLayout()).show(jPanel3, "card2");    
    }//GEN-LAST:event_SaveActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
         ((CardLayout)jPanel3.getLayout()).show(jPanel3, "card2");   
    }//GEN-LAST:event_BackActionPerformed
    static void setframe(GameInterface ds ){
   gi = ds;
   }
    private void ResumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResumeMouseClicked
if(gi!=null){
this.dispose();
    gi.setVisible(true);
    
}        // TODO add your handling code here:
    }//GEN-LAST:event_ResumeMouseClicked

    private void Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save1ActionPerformed
    ((CardLayout)jPanel3.getLayout()).show(jPanel3, "card2");    
    }//GEN-LAST:event_Save1ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
       ((CardLayout)jPanel3.getLayout()).show(jPanel3, "card4");           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked
static boolean getMusic(){
return music;
}
static JPanel getHighScorePanel(){
return higscoresPanel;
}
    static String getPLayerName(){

        return player;
}
    private ArrayList<Integer> highscores=new ArrayList<Integer>();
    private   ArrayList<String> names = new ArrayList<String>();

  String minutes(int remainder){
int mins = remainder / 60;
    remainder = remainder - mins * 60;
    int secs = remainder;
    
 return "00:0"+String.valueOf(mins)+":"+String.valueOf(secs);
}
  Settings set; 
    public   void addin(int seconds , String name){
//int size = highscores.size();

boolean isless=false;
//highscores.add(2);
        
for(int i =0;i<highscores.size();i++){
              if(seconds<=highscores.get(i)){
                  highscores.add(i, seconds);
                  names.add(i,name);
            isless=true;
            break;
              }
   }
      
      //System.out.println(names);
        if(!isless){
            
        if(highscores.size()!=5){
            System.out.println("This condition becomes true");
        
            highscores.add(seconds);
         names.add(name);
        }
        }
        if(highscores.size()==6){
        highscores.remove(highscores.size()-1);
        names.remove(names.size()-1)
                ;
        }
           System.out.println(names);
    System.out.println(highscores);
          
          
         set.loadarray(names,highscores);
   
     updatetext(names,highscores);
   
 }
 
    void updatetext(ArrayList<String> names,ArrayList<Integer>highscores){
  
        for(int i = 0;i<highscores.size();i++){
 
      
     if(i==0){
           Name1.setText(names.get(i));
            time1.setText(minutes(highscores.get(i)));
       Rank1.setVisible(true);
            
     }
          if(i==1){  
           Name2.setText(names.get(i));
           time2.setText(minutes(highscores.get(i)));
       Rank2.setVisible(true);
          }
        if(i==2){
            
            Name3.setText(names.get(i));
         time3.setText(minutes(highscores.get(i)));
      Rank3.setVisible(true);
        }
   if(i==3){
   Name4.setText(names.get(i));
   time4.setText(minutes(highscores.get(i)));
  Rank4.setVisible(true);
   }if(i==4){
   time5.setText(minutes(highscores.get(i)));
       Name5.setText(names.get(i));
   
   Rank5.setVisible(true);
   }
      
    
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JRadioButton Difficult;
    private javax.swing.JRadioButton Easy;
    private javax.swing.JRadioButton Medium;
    public javax.swing.JLabel Name1;
    public javax.swing.JLabel Name2;
    public javax.swing.JLabel Name3;
    public javax.swing.JLabel Name4;
    public javax.swing.JLabel Name5;
    private javax.swing.JLabel Rank1;
    private javax.swing.JLabel Rank2;
    private javax.swing.JLabel Rank3;
    private javax.swing.JLabel Rank4;
    private javax.swing.JLabel Rank5;
    private javax.swing.JLabel Resume;
    private javax.swing.JButton Save;
    private javax.swing.JButton Save1;
    private static javax.swing.JTextField UserName;
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JPanel higscoresPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JLabel time1;
    public javax.swing.JLabel time2;
    public javax.swing.JLabel time3;
    public javax.swing.JLabel time4;
    public javax.swing.JLabel time5;
    // End of variables declaration//GEN-END:variables
}
